language: python
python:
  - '3.7'
cache: pip

install:
  - python --version
  - pip --version
  - pip install pelican
  - pip install Markdown jinja2

script:
  - pelican --version
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - git config --global push.default simple
  - git clone --depth=1 https://github.com/haoqixu/flex theme
  - git clone --depth=1 https://$GH_TOKEN@github.com/haoqixu/haoqixu.github.io _output
  - make DEBUG=1 publish

after_success:
  - cd _output
  - rsync -a --delete --delete-after --exclude '.git' ../output/ ./
  - git add -A .
  - git commit -m "Update from travis, build $TRAVIS_BUILD_NUMBER on $(hostname)"
  - git push --quiet
